// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxcdhauIS8sAIPX7srdu-FIUrCNUx0bNQ',
    appId: '1:146521422465:web:6145b5a72751eb908f6b80',
    messagingSenderId: '146521422465',
    projectId: 'indoor-plant-watering-system',
    authDomain: 'indoor-plant-watering-system.firebaseapp.com',
    databaseURL: 'https://indoor-plant-watering-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'indoor-plant-watering-system.appspot.com',
    measurementId: 'G-33H3V0PLEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwuN7TVO7SI6X-c4XqzCBsibcLgZkVFxQ',
    appId: '1:146521422465:android:73ce0021bf1a28e08f6b80',
    messagingSenderId: '146521422465',
    projectId: 'indoor-plant-watering-system',
    databaseURL: 'https://indoor-plant-watering-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'indoor-plant-watering-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2vuC9YwLomHuyeE8OfjsFbK670uLhTSg',
    appId: '1:146521422465:ios:4ef784ed5f8483cf8f6b80',
    messagingSenderId: '146521422465',
    projectId: 'indoor-plant-watering-system',
    databaseURL: 'https://indoor-plant-watering-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'indoor-plant-watering-system.appspot.com',
    androidClientId: '146521422465-rigor8q88n6450u849lfoq9c5m8tcaoq.apps.googleusercontent.com',
    iosClientId: '146521422465-5p7jbgbq6b1aipm5bh2m8fqunkvltaf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.indoorPlantWateringApp',
  );
}
